import 'package:cloud_firestore/cloud_firestore.dart';

/// Model for appliance usage data saved to Firestore
class ApplianceUsageModel {
  final String id;
  final String applianceId;
  final String applianceName;
  final String applianceIcon;
  final double cost;
  final double kwh;
  final int? watts;
  final int duration; // Duration in seconds
  final double ratePerKwh;
  final Timestamp timestamp;
  final String action; // 'turn_on' | 'turn_off'
  final Timestamp? sessionStartTime;
  final Timestamp? sessionEndTime;
  final String userId;
  final String date; // 'YYYY-MM-DD' for easy querying
  final String month; // 'YYYY-MM' for monthly aggregation

  ApplianceUsageModel({
    required this.id,
    required this.applianceId,
    required this.applianceName,
    required this.applianceIcon,
    required this.cost,
    required this.kwh,
    this.watts,
    required this.duration,
    required this.ratePerKwh,
    required this.timestamp,
    required this.action,
    this.sessionStartTime,
    this.sessionEndTime,
    required this.userId,
    required this.date,
    required this.month,
  });

  factory ApplianceUsageModel.fromMap(String id, Map<String, dynamic> data) {
    return ApplianceUsageModel(
      id: id,
      applianceId: data['applianceId'] ?? '',
      applianceName: data['applianceName'] ?? '',
      applianceIcon: data['applianceIcon'] ?? '',
      cost: (data['cost'] ?? 0.0).toDouble(),
      kwh: (data['kwh'] ?? 0.0).toDouble(),
      watts: data['watts'] != null ? (data['watts'] as num).toInt() : null,
      duration: (data['duration'] ?? 0).toInt(),
      ratePerKwh: (data['ratePerKwh'] ?? 0.0).toDouble(),
      timestamp: data['timestamp'] as Timestamp? ?? Timestamp.now(),
      action: data['action'] ?? 'turn_off',
      sessionStartTime: data['sessionStartTime'] as Timestamp?,
      sessionEndTime: data['sessionEndTime'] as Timestamp?,
      userId: data['userId'] ?? '',
      date: data['date'] ?? '',
      month: data['month'] ?? '',
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'applianceId': applianceId,
      'applianceName': applianceName,
      'applianceIcon': applianceIcon,
      'cost': cost,
      'kwh': kwh,
      if (watts != null) 'watts': watts,
      'duration': duration,
      'ratePerKwh': ratePerKwh,
      'timestamp': timestamp,
      'action': action,
      if (sessionStartTime != null) 'sessionStartTime': sessionStartTime,
      if (sessionEndTime != null) 'sessionEndTime': sessionEndTime,
      'userId': userId,
      'date': date,
      'month': month,
    };
  }

  /// Create a turn_on event
  factory ApplianceUsageModel.turnOn({
    required String applianceId,
    required String applianceName,
    required String applianceIcon,
    required String userId,
    required double ratePerKwh,
    int? watts,
    Timestamp? timestamp,
  }) {
    final now = timestamp ?? Timestamp.now();
    final dateTime = now.toDate();
    final date =
        '${dateTime.year}-${dateTime.month.toString().padLeft(2, '0')}-${dateTime.day.toString().padLeft(2, '0')}';
    final month =
        '${dateTime.year}-${dateTime.month.toString().padLeft(2, '0')}';

    return ApplianceUsageModel(
      id: '', // Will be generated by Firestore
      applianceId: applianceId,
      applianceName: applianceName,
      applianceIcon: applianceIcon,
      cost: 0.0,
      kwh: 0.0,
      watts: watts,
      duration: 0,
      ratePerKwh: ratePerKwh,
      timestamp: now,
      action: 'turn_on',
      sessionStartTime: now,
      userId: userId,
      date: date,
      month: month,
    );
  }

  /// Create a turn_off event with calculated metrics
  factory ApplianceUsageModel.turnOff({
    required String applianceId,
    required String applianceName,
    required String applianceIcon,
    required String userId,
    required double ratePerKwh,
    required int watts,
    required int durationSeconds,
    required Timestamp sessionStartTime,
    Timestamp? timestamp,
  }) {
    final now = timestamp ?? Timestamp.now();
    final dateTime = now.toDate();
    final date =
        '${dateTime.year}-${dateTime.month.toString().padLeft(2, '0')}-${dateTime.day.toString().padLeft(2, '0')}';
    final month =
        '${dateTime.year}-${dateTime.month.toString().padLeft(2, '0')}';

    // Calculate kWh consumed during this session
    final hoursUsed = durationSeconds / 3600.0;
    final sessionKwh = (watts * hoursUsed) / 1000.0;
    final cost = sessionKwh * ratePerKwh;

    return ApplianceUsageModel(
      id: '', // Will be generated by Firestore
      applianceId: applianceId,
      applianceName: applianceName,
      applianceIcon: applianceIcon,
      cost: cost,
      kwh: sessionKwh,
      watts: watts,
      duration: durationSeconds,
      ratePerKwh: ratePerKwh,
      timestamp: now,
      action: 'turn_off',
      sessionStartTime: sessionStartTime,
      sessionEndTime: now,
      userId: userId,
      date: date,
      month: month,
    );
  }
}
