// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6W02Sm2ShrmNtmDTe9sOV1dQD3hGSf4M',
    appId: '1:281073543283:web:4afab462085088b265e206',
    messagingSenderId: '281073543283',
    projectId: 'capstonefinal593',
    authDomain: 'capstonefinal593.firebaseapp.com',
    storageBucket: 'capstonefinal593.firebasestorage.app',
    databaseURL:
        'https://capstonefinal593-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6W02Sm2ShrmNtmDTe9sOV1dQD3hGSf4M',
    appId: '1:281073543283:android:4afab462085088b265e206',
    messagingSenderId: '281073543283',
    projectId: 'capstonefinal593',
    authDomain: 'capstonefinal593.firebaseapp.com',
    storageBucket: 'capstonefinal593.firebasestorage.app',
    databaseURL:
        'https://capstonefinal593-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq5kh0SZpeenkwtCP6ipzlHKk48LSDuuo',
    appId: '1:281073543283:ios:cdfbb697ac9eaa2f65e206',
    messagingSenderId: '281073543283',
    projectId: 'capstonefinal593',
    databaseURL:
        'https://capstonefinal593-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'capstonefinal593.firebasestorage.app',
    androidClientId:
        '281073543283-ornnrv80rq9u2as3ad552pon8dfprpsr.apps.googleusercontent.com',
    iosClientId:
        '281073543283-ekc52o4nhu39mf089a4anr8raue7ulji.apps.googleusercontent.com',
    iosBundleId: 'com.example.exerciseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq5kh0SZpeenkwtCP6ipzlHKk48LSDuuo',
    appId: '1:281073543283:ios:cdfbb697ac9eaa2f65e206',
    messagingSenderId: '281073543283',
    projectId: 'capstonefinal593',
    databaseURL:
        'https://capstonefinal593-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'capstonefinal593.firebasestorage.app',
    androidClientId:
        '281073543283-ornnrv80rq9u2as3ad552pon8dfprpsr.apps.googleusercontent.com',
    iosClientId:
        '281073543283-ekc52o4nhu39mf089a4anr8raue7ulji.apps.googleusercontent.com',
    iosBundleId: 'com.example.exerciseApp',
  );
}
